# Generated by Django 3.0.6 on 2020-05-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='书名')),
                ('author', models.CharField(blank=True, max_length=50, null=True, verbose_name='作者')),
            ],
            options={
                'db_table': 'book',
            },
        ),
    ]
